### ISSUE TITLE
question: What is the Project Status?

### ISSUE THREAD

**Issue by s0kil** [Regaez/grav-plugin-api#6]
I'm planning to use this project in my application, What is the status of this project? Is it still being maintained?

**Comment by khanduras** [comment]
It looks really well done. I wish for some more documentation and to be able to access data from the API.

**Comment by Regaez** [comment]
@s0kil @khanduras Thanks for the interest! 

I had a long hiatus from GravCMS, but I am trying to find time to work on this further. I am still keen on developing this plugin, since there _still_ seems to be no alternative. I can't guarantee any release date, but I shall see what I can do about getting something stable (and useful!) up and running.

I am working on _thoroughly_ documenting all the existing functionality (see #11) and will then look to improve/add more features.

**Comment by khanduras** [comment]
Sounds awesome @Regaez Thanks for the update
